# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EasyDial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyDial

pod 'Firebase/Core', '~> 4.5.0'
pod 'Firebase/Auth', '~> 4.5.0'
pod 'Firebase/Database', '~> 4.5.0'
pod 'GoogleSignIn'

end
